# These are supported funding model platforms

ko_fi: n0vember24
buy_me_a_coffee: n0vember24
thanks_dev: n0vember24
patreon: n0vember24
custom: [https://my.click.uz/clickp2p/7F6D001B56259B7A0BFEE3C8CF1452816EEA24EF0F3BFD928483E925C93EA4A0] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# open_collective: # Replace with a single Open Collective username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# polar: # Replace with a single Polar username
